version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - CONTEXT_SERVICE_URL=http://context-service:3002
      - AI_SERVICE_URL=http://ai-service:3003
      - LEARNING_SERVICE_URL=http://learning-service:3004
      - FILE_SERVICE_URL=http://file-service:3005
    depends_on:
      - context-service
      - ai-service
      - learning-service
      - file-service
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules

  # Context Service
  context-service:
    build: ./services/context-service
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/context-service:/app
      - /app/node_modules

  # AI Service
  ai-service:
    build: ./services/ai-service
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./services/ai-service:/app
      - /app/node_modules

  # Learning Service
  learning-service:
    build: ./services/learning-service
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/learning-service:/app
      - /app/node_modules

  # File Service
  file-service:
    build: ./services/file-service
    ports:
      - '3005:3005'
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/file-service:/app
      - /app/node_modules
      - ./uploads:/app/uploads

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
